# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/olives/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter pine olives,$(TARGET_DEVICE)),)

endif
